task:
  name: "Setting Up, Syncing, Building and Uploading "
  timeout_in: 240m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G
        
  Sync_script:
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-20.0 -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone https://github.com/atharvnegi/android_kernel_xiaomi_selene kernel/xiaomi/selene
      - git clone https://github.com/Atharv-Supremacy/android_device_xiaomi_selene device/xiaomi/selene
      - git clone https://github.com/Atharv-Supremacy/android_vendor_xiaomi_selene vendor/xiaomi/selene

  Build_script:
      - cd ~/work
      - sudo apt install clang-14 -y
      - . build/envsetup.sh
      - lunch lineage_selene-userdebug
      - mka bacon
     
  Upload_script:
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - curl -sL https://git.io/file-transfer | sh
      - ./transfer wet *.zip
