task:
  name: "Setting Up, Syncing, Building and Uploading "
  timeout_in: 240m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G
        
  Sync_script:
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-18. 1-g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone https://github.com/samsung-m11q/android_kernel_samsung_m11q kernel/samsung/m11q
      - git clone https://github.com/Atharv-Supremacy/android_vendor_samsung_m11q vendor/samsung/m11q
      - git clone https://github.com/Atharv-Supremacy/android_device_samsung_m11q device/samsung/m11q

  Build_script:
      - cd ~/work
      - . build/envsetup.sh
      - lunch lineage_m11q-userdebug
      - mka bacon
     
  Upload_script:
      - cd ~/work
      - cd out/target/product/m11q
      - curl -sL https://git.io/file-transfer | sh
      - ./transfer wet *.zip
